#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import csv

"""检测所有的csv文件列顺序是否按给定的list顺序排列"""

# ========= 配置 =========
DIR_PATH = r"D:\\tmp\\cc\\v4\\bak_csv_v2"  # 替换成你的 CSV 文件目录
OUTPUT_FILE = r"D:\\tmp\\cc\\v4\\check_head_is_order.txt"

# 表头顺序
EXPECTED_HEADER = [
"data_id",
"fund_loan_result",
"annual_rate",
"loan_date",
"loan_id",
"loan_amount",
"loan_periods",
"loan_time",
"monthly_rate",
"repay_method",
"step_status",
"status",
"receivable_guarantee_fee",
"total_amount_diff",
"current_period_1",
"repay_date_1",
"fund_interest_1",
"fund_principal_1",
"fund_total_1",
"cumulative_repaid_1",
"period_diff_1",
"guarantee_fee_1",
"calculated_guarantee_fee_1",
"current_period_2",
"repay_date_2",
"fund_interest_2",
"fund_principal_2",
"fund_total_2",
"cumulative_repaid_2",
"period_diff_2",
"guarantee_fee_2",
"calculated_guarantee_fee_2",
"current_period_3",
"repay_date_3",
"fund_interest_3",
"fund_principal_3",
"fund_total_3",
"cumulative_repaid_3",
"period_diff_3",
"guarantee_fee_3",
"calculated_guarantee_fee_3",
"current_period_4",
"repay_date_4",
"fund_interest_4",
"fund_principal_4",
"fund_total_4",
"cumulative_repaid_4",
"period_diff_4",
"guarantee_fee_4",
"calculated_guarantee_fee_4",
"current_period_5",
"repay_date_5",
"fund_interest_5",
"fund_principal_5",
"fund_total_5",
"cumulative_repaid_5",
"period_diff_5",
"guarantee_fee_5",
"calculated_guarantee_fee_5",
"current_period_6",
"repay_date_6",
"fund_interest_6",
"fund_principal_6",
"fund_total_6",
"cumulative_repaid_6",
"period_diff_6",
"guarantee_fee_6",
"calculated_guarantee_fee_6",
"current_period_7",
"repay_date_7",
"fund_interest_7",
"fund_principal_7",
"fund_total_7",
"cumulative_repaid_7",
"period_diff_7",
"guarantee_fee_7",
"calculated_guarantee_fee_7",
"current_period_8",
"repay_date_8",
"fund_interest_8",
"fund_principal_8",
"fund_total_8",
"cumulative_repaid_8",
"period_diff_8",
"guarantee_fee_8",
"calculated_guarantee_fee_8",
"current_period_9",
"repay_date_9",
"fund_interest_9",
"fund_principal_9",
"fund_total_9",
"cumulative_repaid_9",
"period_diff_9",
"guarantee_fee_9",
"calculated_guarantee_fee_9",
"current_period_10",
"repay_date_10",
"fund_interest_10",
"fund_principal_10",
"fund_total_10",
"cumulative_repaid_10",
"period_diff_10",
"guarantee_fee_10",
"calculated_guarantee_fee_10",
"current_period_11",
"repay_date_11",
"fund_interest_11",
"fund_principal_11",
"fund_total_11",
"cumulative_repaid_11",
"period_diff_11",
"guarantee_fee_11",
"calculated_guarantee_fee_11",
"current_period_12",
"repay_date_12",
"fund_interest_12",
"fund_principal_12",
"fund_total_12",
"cumulative_repaid_12",
"period_diff_12",
"guarantee_fee_12",
"calculated_guarantee_fee_12",
"current_period_13",
"repay_date_13",
"fund_interest_13",
"fund_principal_13",
"fund_total_13",
"cumulative_repaid_13",
"period_diff_13",
"guarantee_fee_13",
"calculated_guarantee_fee_13",
"current_period_14",
"repay_date_14",
"fund_interest_14",
"fund_principal_14",
"fund_total_14",
"cumulative_repaid_14",
"period_diff_14",
"guarantee_fee_14",
"calculated_guarantee_fee_14",
"current_period_15",
"repay_date_15",
"fund_interest_15",
"fund_principal_15",
"fund_total_15",
"cumulative_repaid_15",
"period_diff_15",
"guarantee_fee_15",
"calculated_guarantee_fee_15",
"current_period_16",
"repay_date_16",
"fund_interest_16",
"fund_principal_16",
"fund_total_16",
"cumulative_repaid_16",
"period_diff_16",
"guarantee_fee_16",
"calculated_guarantee_fee_16",
"current_period_17",
"repay_date_17",
"fund_interest_17",
"fund_principal_17",
"fund_total_17",
"cumulative_repaid_17",
"period_diff_17",
"guarantee_fee_17",
"calculated_guarantee_fee_17",
"current_period_18",
"repay_date_18",
"fund_interest_18",
"fund_principal_18",
"fund_total_18",
"cumulative_repaid_18",
"period_diff_18",
"guarantee_fee_18",
"calculated_guarantee_fee_18",
"current_period_19",
"repay_date_19",
"fund_interest_19",
"fund_principal_19",
"fund_total_19",
"cumulative_repaid_19",
"period_diff_19",
"guarantee_fee_19",
"calculated_guarantee_fee_19",
"current_period_20",
"repay_date_20",
"fund_interest_20",
"fund_principal_20",
"fund_total_20",
"cumulative_repaid_20",
"period_diff_20",
"guarantee_fee_20",
"calculated_guarantee_fee_20",
"current_period_21",
"repay_date_21",
"fund_interest_21",
"fund_principal_21",
"fund_total_21",
"cumulative_repaid_21",
"period_diff_21",
"guarantee_fee_21",
"calculated_guarantee_fee_21",
"current_period_22",
"repay_date_22",
"fund_interest_22",
"fund_principal_22",
"fund_total_22",
"cumulative_repaid_22",
"period_diff_22",
"guarantee_fee_22",
"calculated_guarantee_fee_22",
"current_period_23",
"repay_date_23",
"fund_interest_23",
"fund_principal_23",
"fund_total_23",
"cumulative_repaid_23",
"period_diff_23",
"guarantee_fee_23",
"calculated_guarantee_fee_23",
"current_period_24",
"repay_date_24",
"fund_interest_24",
"fund_principal_24",
"fund_total_24",
"cumulative_repaid_24",
"period_diff_24",
"guarantee_fee_24",
"calculated_guarantee_fee_24",
"source"
]

# ========= 主程序 =========
results = []

for filename in os.listdir(DIR_PATH):
    if filename.lower().endswith('.csv'):
        print(f"正在处理文件: {filename}")  # 打印正在处理的文件
        file_path = os.path.join(DIR_PATH, filename)
        try:
            with open(file_path, 'r', encoding='utf-8-sig') as f:
                reader = csv.reader(f)
                header = next(reader)
                if header == EXPECTED_HEADER:
                    results.append(f"{filename}: OK")
                else:
                    results.append(f"{filename}: WRONG ORDER")
        except Exception as e:
            results.append(f"{filename}: ERROR ({e})")

# 写入结果
with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
    for line in results:
        f.write(line + "\n")

print(f"检查完成，结果已写入 {OUTPUT_FILE}")
